### ISSUE TITLE
Mouse trail does not align vertically

### ISSUE THREAD

**Issue by jordanbrotherton** [ufosc/Club_Website_2#212] opened 2024-09-10 22:43 UTC
On the header animation, the red trail that follows the mouse cursor increasingly becomes misaligned the further away the mouse is from the middle of the animation area. Looking into it seems to be related to the `onPointerMove` function at [`src/components/Animation/Renderer.tsx`](https://github.com/ufosc/Club_Website_2/blob/main/src/components/Animation/Renderer.tsx#L151), potentially not accounting for the header?

Attached is a video showing the trail on multiple browsers. Shown on the left is a Gecko based browser (Firefox), the middle is a Blink based browser (Chromium), and the right is a WebKit based browser (GNOME Web).

https://github.com/user-attachments/assets/90fa18c0-ecb9-4699-9279-c9b6927f5ae5

**Comment by zeim839** [comment] 2024-09-11 19:03
The issue is caused by the depth perspective of the background animation. The pointer is supposed to be cast onto the wave surface in the background, but we've scaled and rotated the scene and so now it looks like its misaligned. 

I'm aware of this but honestly we've never really considered it to be an issue. I'll be closing this issue since this isn't a priority right now, but feel free to come up with a solution if you're still interested. Massive thank you for taking the time to investigate this though.

**Closed by zeim839** 2024-09-11 19:03 UTC
